### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [multiformats/rust-multihash#1]
Hey @dignifiedquire!

Thanks so much for this. As you may know, we recently created the [Multiformats](//github.com/multiformats) organization to be a home for all of the multiformats - multiaddr, multihash, etc. Would you be interested in moving this repository to that organization? You would still have admin rights on the repository, but it would be a part of a wider organization. This would mean more relevant eyes on it (most likely) and better cross-repository issue tracking. We'd also add a line mentioning you as the original author, and of course your commits would stay the same. 

Of course, keeping it on your profile is also cool; we'll still link to this from the main multihash repository at github.com/multiformats/multihash.

Thanks for taking the time to read this. 👍 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by RichardLitt** [comment]
Unless you feel that Google's should be moved there, first? Or should it moved as well? Thoughts?

**Comment by dignifiedquire** [comment]
Given that Googles is nowhere near as feature complete as this and hasn't been touched in a while, let's move this one :)

**Comment by dignifiedquire** [comment]
Lost my access again :(

**Comment by RichardLitt** [comment]
Fixed. We're all good?

**Comment by jbenet** [comment]
Leave the google one where it is.
