### ISSUE TITLE
Use const generics

### ISSUE THREAD

**Issue by rklaehn** [multiformats/rust-multihash#114]
They are finally there: https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html

Should help a lot with the very verbose types we currently use...

**Comment by mriise** [comment]
would changing the API to look more like

```rust
Multihash::SHA_2<SIZE_BYTES>
```

be the right move for this or do we keep tables the way they are, and maybe just add this on top of what we have @vmx

**Comment by vmx** [comment]
I haven't thought about this yet. My intuition is that I probably would keep things as they are and just doing a move to const generics. A next step would then be to improve/change the API if it makes sense. Though as I haven't looked at it, it might also make sense to do it at once.

@mriise If you're happy to take comments, feel free to PR whatever you currently have and then we can discuss details on the PR.
