### ISSUE TITLE
Heap allocation for large hashes

### ISSUE THREAD

**Issue by mriise** [multiformats/rust-multihash#121]
An implementation using https://docs.rs/smallvec/1.6.1/smallvec/struct.SmallVec.html would allow for us to keep stack allocating for smaller sizes, but easily enough spill onto heap if the hash is bigger than the specified allocated size.

The question is would `alloc_size` still be a hard limit with this, or the just the allocated stack size with whatever `usize` is to limit heap?

This should be close to a drop in replacement for the array we use now to store the digest in `Multihash` without affecting end user API

**Comment by rklaehn** [comment]
We had a similar thing some time ago. It would stack allocate up to a certain size, then spill on the heap.

The reason for the current approach is that it allows a multihash to be `Copy`, which is very useful for both performance and eliminating boilerplate.

**Comment by dvc94ch** [comment]
@mriise what use case do you have for large hashes?

**Comment by rklaehn** [comment]
The max size of a Multihash is already configurable via the Size parameter. This will be a bit nicer once we fully integrate const generics.

So if you frequently deal with multihashes of a large size, let's say 1024, you can just configure it via the type parameter.

The only case where this is wasteful is if your typical multihash is small (32 bytes) and occasionally you get a very large multihash. But I think this is sufficiently rare in practice that it does not justify the ugliness of making multihash non-`Copy`.

I love the fact that with the current impl a multihash is `Copy` and all small structs that include a multihash can therefore also be `Copy`.

**Comment by vmx** [comment]
I'd consider arbitrary sized Multihashes a special case. Usually fixed sized ones should be good enough.

In case you have the use case, e.g. you want to store large identity hashes in IPFS (which I don't recommend, but one might do), you could use a library that does heap allocations. So perhaps (I'm really not sure about it) it would make sense to also have a separate Multihash implementation that is only doing heap allocations, which will (hopefully) be a lot simpler (code complexity wise).
