### ISSUE TITLE
Merging work from yatima-inc/sp-multihash

### ISSUE THREAD

**Issue by johnchandlerburnham** [multiformats/rust-multihash#144]
Hi, I talked briefly to @Stebalien about merging some of  the work from our https://github.com/yatima-inc/sp-multihash no_std fork. Happy to send PRs, but wanted to ask a few questions first:

1. Const-Generics:`sp-multihash` is on rust 1.54-nightly, so we were able to adapt @mriise's excellent #116. It looks like you guys are waiting on https://github.com/rust-lang/rust/issues/44265 hitting stable Rust first before merging #116. To me, the usability regression reported in [this comment](https://github.com/multiformats/rust-multihash/pull/116/files#r649205179) seems acceptable compared to the usability gains from not having to drag typenums around everywhere. Plus, `const-generics` also opens up some really exciting refactoring possiblities, like @Stebalien's neat idea for using DSTs to erase the size-info here: https://github.com/yatima-inc/sp-cid/issues/5. Since waiting some weeks/months for stable GATs seems not ideal, I'm wondering if we can figure out some way around this:
 - Is the stable requirement an absolute for this lib? Or maybe we could make a "nightly" `rust-multihash` branch/release so that development here isn't impacted by rustc as much?
 - Alternatively, is there a way to make the above usability regression acceptable to you, using only stable `const-generics`?

2. ByteCursor: Our `no_std` work removes `std::io` functions for reading/writing in favor of our [bytecursor](https://github.com/yatima-inc/bytecursor) library. This can be added independently of Const-Generics.
 - Is the bytecursor dependency acceptable here? What about [`sp-std`](https://docs.rs/sp-std/3.0.0/sp_std/)?
 - Do you want to keep the `std::io`, functions gated behind the `std` feature via pragmas? If so, should `std` still be default?
 
 3. Nix: We've added a Nix build to `sp-multihash`, and can PR (independently of the above) to add one here (preview: https://github.com/yatima-inc/rust-multihash/pull/1/files), if that's of interest.

**Comment by mriise** [comment]
`#[cfg(feature = "std")]` and `#[cfg(not(feature = "std"))]` can be placed pretty much anywhere if I understood what 3 was asking

**Comment by johnchandlerburnham** [comment]
Okay, it's sounding like we should focus on sending PRs for ByteCursor and Nix, and waiting on `const-generics`. We'll get to work on PRs for those two.

> Given that sp-std is basically just a core/std switch, I see no reason not to depend on it.

To clarify the double negative, you mean we should depend on sp-std or we should not, and use core, alloc, etc directly instead? 

> Would it be possible to make ByteCursor implement the standard traits iff the "std" feature is enabled?

Doing the `std::io` traits in bytecursor itself is a good idea, I'll look into that.

**Comment by mriise** [comment]
I think it might be good to use an implementation already made for using read/write in no_std enviornments 

[this one seems goood](https://docs.rs/core2/0.3.2/core2/) and has const generic support

[this one is is auto generated](https://github.com/jethrogb/rust-core_io)

**Comment by vmx** [comment]
@samuelburnham I think with the 0.16 release we have incorporated everything from your work on sp-multihash. If something is missing, please open an issue or re-open this one.
