### ISSUE TITLE
Multihashes can be formed with incorrect sizes 

### ISSUE THREAD

**Issue by mriise** [multiformats/rust-multihash#157]
If a multihash is read from bytes, there are no checks to assert that the code and size read match, so the below pseudo code can be read from bytes and sent along as if it were correct.
```rust
Multihash {
    code: SHA2_512,
    size: 10
    digest: [0; 10]
}
``` 
along with some other variations

**Comment by mriise** [comment]
The fix would be to assert the size read from the varint matches with the expected size from the code. From there, the correct amount of bytes should be read life can continue normally. There may be some other spots where the digest size should be double checked, but I have not read that far into this yet.

**Comment by Stebalien** [comment]
This is a feature, not a bug. "size 10 SHA2_512" means a SHA2_512 hash truncated to 10 bytes.

I guess we _could_ verify that the user doesn't specify a codec with _more_ bytes than possible, but there isn't really much value in that.
