### ISSUE TITLE
Help: How to use serde(Serialize, Deserialize) on multihash?

### ISSUE THREAD

**Issue by fishseabowl** [multiformats/rust-multihash#175]
I search the previous issue: Make multihash serializable with serde #62. And I got: Multihash is now serializable with Serde (it's not released yet, but it's available on HEAD.

I still don't know how to do it. 

Could you help provide some codes how to use serde on multihash?

**Comment by vmx** [comment]
Have you enabled the `serde-codec` feature?

**Comment by fishseabowl** [comment]
Got it. Thanks
