### ISSUE TITLE
Remove `Code::Identity` support

### ISSUE THREAD

**Issue by Stebalien** [multiformats/rust-multihash#194]
1. The feature is technically opt in, but features are _unified_ so the entire program will be "opted in" to supporting identity hashes if any component needs to support them.
2. It's _ridiculously_ easy to end up panicing based on user inputs.

Possible solutions:

1. Make `Code::digest` return a result. This is likely a non-starter due to mass breakage and the number of `unwraps` it would introduce.
2. Make `Cid` dynamically allocated. Also a massive refactor, and a non-starter.
3. Remove it from the default `Code`.

Honestly, I think the best bet is to remove the feature, and maybe export an `IDENTITY_CODE` constant, or even a `identity_hash` free-function that returns a result. My reasoning is that the current identity "code" is pretty much unusable without special casing anyways, and is a massive foot-gun.

**Comment by Stebalien** [comment]
cc @dignifiedquire @vmx

**Comment by vmx** [comment]
The with removing the `identity` feature is that libp2p (https://github.com/libp2p/rust-libp2p/blob/5291011c73f8eaf44b3ba4ada873d888ff26e703/core/Cargo.toml#L26) and Forest (https://github.com/ChainSafe/forest/blob/e708777ff6d28aa08ff47560cd62212dfe2fbbb7/node/forest_libp2p/Cargo.toml#L24) are using it atm.

**Comment by vmx** [comment]
My expectations for "power users" like the FVM were, that you wouldn't rely on the default code table, but you would create your own one, specific to the project. For example the default table is using 64 bytes allocations, I guess for the FVM 32 bytes would be enough.

**Comment by mriise** [comment]
I think it mostly comes down to how its expected to behave, if its supposed full to copy everything into itself, then thats not something that you are able to implement without allocating. (this does not fit in well the design of this crate)

if the expectation is that it copies as much as it can, we can truncate anything that doesnt fit inside of the the const sized array.
its a simple fix if you just want to truncate 
```rust
fn update(&mut self, input: &[u8]) {
    let end = (self.i + input.len()).min(self.bytes.len());
    self.bytes[self.i..end].copy_from_slice(&input[..end]);
    self.i = end;
} 
```

assuming you want to have everything and you know the size is under S (but bigger than the usually allocated), you could  use 
```rust
let mh = Multihash::<128>::wrap(0x00, &src).unwrap();
```
though that could end in weird trait interop with the normally generated multihashes

**Comment by vmx** [comment]
> 1. Special case it everywhere and check to make sure you're not feeding more than 64 bytes to the identity hash function. If you're doing this, there's little point in even _providing_ a `Code::Identity` (rather than a simple `make_identity_hash` helper function that's actually safe).

To me the usual use case, that also [libp2p is using](https://github.com/libp2p/rust-libp2p/blob/96103ee590b60d5c7ed7ca5253a7f7ddd802ce76/core/src/peer_id.rs#L60-L66) is "is the data smaller than a certain size, use the data directly, else hash it". In that case you always check the size and can be sure it fits into your `Cid`.

The identity hash is something that needs to be used with care, hence it's behind a feature flag.

**Comment by Stebalien** [comment]
> To me the usual use case, that also [libp2p is using](https://github.com/libp2p/rust-libp2p/blob/96103ee590b60d5c7ed7ca5253a7f7ddd802ce76/core/src/peer_id.rs#L60-L66) is "is the data smaller than a certain size, use the data directly, else hash it". In that case you always check the size and can be sure it fits into your Cid.

Sure, but in that case, one could just call `Multihash::wrap(0, ...)`.

> The identity hash is something that needs to be used with care, hence it's behind a feature flag.

Unfortunately, feature flags are additive. That's what makes this so dangerous.
