### ISSUE TITLE
Panic on size being smaller than default

### ISSUE THREAD

**Issue by hummingly** [multiformats/rust-multihash#213]
I was looking through the source code and found this for the `Blake3Hasher.finalize()` method. 

https://github.com/multiformats/rust-multihash/blob/f1d20e94a0341d0982beb22df37c29d43ace6eb2/src/hasher_impl.rs#L124

This will always panic if `S` is less than 32 and the same line of code appears for other hasher implementations too. The fix would be to compute the minimum length and use that to create the byte slices.

```rs
let digest = self.state.finalize();
let len = digest.len().min(S);
let digest_bytes = digest.as_bytes()[..len];
let digest_out = &mut self.digest[..len];
digest_out.copy_from_slice(digest_bytes);
digest_out
```

**Comment by vmx** [comment]
I don't think it would panic, but I might miss something.

So let's say `S` is 16 and `digest_bytes.len()` is 32. Then `digest_bytes.len().max(S)` would be 32.

So `Blake3Hasher.finalize()` makes sure that the returned value has at least `S` bytes, but maybe more. Then later, when the hash is used (that mostly happens in the `multihash-derive` crate), the result goes through `Multihash::wrap()`, which will error (not panic) in case the has is too long: 

https://github.com/multiformats/rust-multihash/blob/f1d20e94a0341d0982beb22df37c29d43ace6eb2/src/multihash.rs#L102-L104

**Comment by hummingly** [comment]
My code looks like that where DIGEST_SIZE is 32 right now.

```rs
pub struct ContentHasher(Blake3Hasher<DIGEST_SIZE>);

impl ContentHasher {
    pub fn new() -> ContentHasher {
        ContentHasher(Blake3Hasher::default())
    }

    pub fn write(&mut self, input: &[u8]) {
        self.0.update(input);
    }

    pub fn finish(&mut self) -> ContentHash {
        let hash = multihash::Code::Blake3_256.wrap(self.0.finalize()).unwrap();
        hash.resize::<DIGEST_SIZE>().unwrap()
    }

    pub fn reset(&mut self) {
        self.0.reset();
    }
}
```

However, if I were to set it to something smaller than the default digest size (32), it will panic. The reason is an out of bounds indexing error due the array `digest` in the `Blake3Hasher` struct as I explained in the previous comment.

https://github.com/multiformats/rust-multihash/blob/f1d20e94a0341d0982beb22df37c29d43ace6eb2/src/hasher_impl.rs#L100-L103

> So Blake3Hasher.finalize() makes sure that the returned value has at least S bytes, but maybe more. Then later, when the hash is used (that mostly happens in the multihash-derive crate), the result goes through Multihash::wrap(), which will error (not panic) in case the has is too long:

It is the other way around. The length will always be S or smaller because `Blake3Hasher.finalize()` returns a slice to the array `digest` in `Blake3Hasher`.

Do you consider it a user error to use an S smaller than the default size of the hash?

**Comment by mriise** [comment]
Blake3 was originally intended to be flexible like this, but some implementation details had kept me away at the time but has since been fixed. see #130 
The Code table being generic over Blake Digest sizes is still something to be solved, either through more proc macro magic or new const generic things.

**Comment by mriise** [comment]
quick note for transparency, this was a bit more broken than this issue mentions, since the digest returned by blake3 was only 32 bytes, anything bigger would've been filled with `0`s 

...fun
