### ISSUE TITLE
Blake2 support

### ISSUE THREAD

**Issue by ghost** [multiformats/rust-multihash#22]
I was wondering about what it would take to add blake2 support. Presently it looks like the codes for blake hashes are u16, so other than adding the types + hashing, I'd need to change [this](https://github.com/multiformats/rust-multihash/blob/master/src/hashes.rs#L38) function signature and anything depending on it?

Anyway, this lib is something I really need, and I'm interested in helping out :)

**Comment by leeola** [comment]
Hello. @wjh did you ever get any traction on this? Any blockers worth mentioning?

**Comment by cyphar** [comment]
Blake2b and Blake2s are now supported (though only a few lengths are supported).

**Comment by dvc94ch** [comment]
@vmx close?

**Comment by vmx** [comment]
No, there are a lot of Blake2 variants, only a small subset is currently supported.

**Comment by vmx** [comment]
I'm closing issues about adding new hash algorithms. It's clear that lots of them are missing. There is no point of having separate issues for them. Feel free to submit PRs if you need one implemented.
