### ISSUE TITLE
Add getter for inner array

### ISSUE THREAD

**Issue by mriise** [multiformats/rust-multihash#220]
We have `fn digest(&self) -> &[u8` though it is helpful to also have `fn digest_arr(&self) -> [u8; S]` for `Multihash`

```rust 
fn digest_arr(&self) -> &[u8; S] {
    self.digest
}
```

**Comment by vmx** [comment]
What would it be used for it? Wouldn't you always want it trimmed to the actual size of the digest, hence use `digest()`?

**Comment by mriise** [comment]
The idea was more to allow for moving of the underlying data which requires `Sized`, though if you are moving it would me more like adding an `fn into_inner` instead

**Comment by vmx** [comment]
A `into_inner` could make sense. Generally spoken I'm a fan of keeping an API as small as possible and only adding things when really needed (this might be the case here). And also I like not exposing internals, which I consider the internal array to be.
