### ISSUE TITLE
Implement ripemd160

### ISSUE THREAD

**Issue by Stebalien** [multiformats/rust-multihash#225]
Code: 0x1053

This hash function is used in Ethereum, Bitcoin, etc. Specifically, I need support for this hash function in the FVM.

**Comment by mriise** [comment]
likely https://docs.rs/ripemd/0.1.1/ripemd/ or https://docs.rs/cryptoxide/0.4.2/cryptoxide/ (maybe https://docs.rs/bitcoin_hashes/0.11.0/bitcoin_hashes/ ?)

**Comment by mriise** [comment]
i would prefer ripemd since it is part of RustCrypto and is more likely to stay maintained https://github.com/RustCrypto/hashes/tree/master/ripemd

**Comment by Stebalien** [comment]
Yeah, the RustCrypto one seems like the best choice. It also targets WASM.
