### ISSUE TITLE
CI tries to run `fmt` with unstable feature and will always fail

### ISSUE THREAD

**Issue by mriise** [multiformats/rust-multihash#227]
https://github.com/multiformats/rust-multihash/commit/6235d260e7e95a51fdf697940fda0b02eb9e9434 was intended to be a PR (sorry...) 

the alternative is to disable unstable `format_code_in_doc_comments`, which I am also ok with

comments @vmx?

**Comment by vmx** [comment]
I cannot reproduce it, hence I've opened a PR to revert that change at https://github.com/multiformats/rust-multihash/pull/228.

The CI is still green and if I add wrong formatting it correctly fails: https://github.com/multiformats/rust-multihash/runs/7762560203?check_suite_focus=true

**Comment by mriise** [comment]
hm, it must've been an a user issue...
