### ISSUE TITLE
Maintain a CHANGELOG.md

### ISSUE THREAD

**Issue by mxinden** [multiformats/rust-multihash#248]
As a downstream user, it would be very helpful to have a changelog for each release. A changelog would allow downstream users to quickly understand the impact of an update like https://github.com/multiformats/rust-multiaddr/pull/63.

I don't have a strong opinion on a format, though favor https://keepachangelog.com/ for the sake of consistency with other projects.

Would this be an option for this project as well?

Thanks for all the work here.
Max - Happy downstream user

**Comment by vmx** [comment]
Yes, it surely would make sense. Given that we (mostly) follow https://www.conventionalcommits.org/en/v1.0.0/, we could even auto-generate one and clean it up before committing. I can only speak for myself, but this didn't happen in the past as I hardly even found the time to do minimal maintenance on this library.

**Comment by vmx** [comment]
We now have a changelog!

**Comment by mxinden** [comment]
:pray: Thanks @vmx!
