### ISSUE TITLE
No way to `encode` a digest directly?

### ISSUE THREAD

**Issue by leavehouse** [multiformats/rust-multihash#25]
# Problem

If you have a hash digest `digest: &[u8]` and you want to `encode` that into multihash bytes, you're out of luck if you're using `rust-multihash` currently. This is because `encode` expects un-hashed data as input. Instead, you must do something like this manually:

```
    let hash_alg = multihash::Hash::SHA1; 
    let mut mh = Vec::with_capacity(digest.len() + 2); 
    mh.push(hash_alg.code()); 
    mh.push(hash_alg.size()); 
    mh.extend_from_slice(digest); 
```

In contrast, `go-multihash`'s `Encode` function does not hash your data for you, so you can directly pass in a digest.

# Potential solutions

This could be remedied with a new encoding function that expects a hash digest, maybe something named `encode_digest`? However, perhaps we should consider changing the way `encode` works. It would be a breaking change, but it would bring it in-line with how go-multihash works.

**Comment by vmx** [comment]
There is now a function called `multihash::wrap()` where you can encode a multihash from an existing digest.
