### ISSUE TITLE
Replace or Upgrade Tarpaulin Code Coverage

### ISSUE THREAD

**Issue by iamjpotts** [multiformats/rust-multihash#265]
`tarpaulin` may be incompatible with newer versions of Node and cause CI failures.

#264 disables the code coverage step in CI.

I don't have a view as to what direction to take afterwards, but that probably depends on if/when [tarpaulin #22](https://github.com/actions-rs/tarpaulin/pull/22) gets released.

**Comment by vmx** [comment]
Other options are:
 - using tarpaulin directly: https://github.com/xd009642/tarpaulin#github-actions
 - llvm-cov: https://github.com/taiki-e/cargo-llvm-cov#continuous-integration ,

**Comment by vmx** [comment]
This was fixed by https://github.com/multiformats/rust-multihash/pull/295.
