### ISSUE TITLE
Split crate into `multihash`, `multihash-codetable` and `multihash-derive`

### ISSUE THREAD

**Issue by thomaseizinger** [multiformats/rust-multihash#266]
As discussed in https://github.com/multiformats/rust-multihash/issues/259.

This issue tracks the splitting up into smaller crates for the purpose of a more stable API.

**Comment by vmx** [comment]
Would it be an issue to have `multihash-derive-impl` and `miltihash-derive` in a single crate? I'd expect that most people would use them together anyway. Though I might be missing something.

**Comment by thomaseizinger** [comment]
> Would it be an issue to have `multihash-derive-impl` and `miltihash-derive` in a single crate? I'd expect that most people would use them together anyway. Though I might be missing something.

The problem is that a proc-macro cannot declare regular Rust symbols like traits or structs because proc-macros are compiled for the host machine and the actual crates for the specified target.

Thus, the types like `MultihashDigest`, `Hasher` and `UnsupportedCode` cannot live next to the proc macro. To make things easier to use though, the macro from the `-impl` crate is typically re-exported, meaning users still just depend on `multihash-derive`.

I've implemented this here already: https://github.com/multiformats/rust-multihash/pull/272

As you can see, someone defining their own codetable would only depend on `multihash-derive` and get everything they need. Someone that just needs the data structure `Multihash` would depend on `multihash`.

**Comment by vmx** [comment]
Thanks for the explanation, that makes sense. Having this documented should make it easy enough to follow as the `multihash-derive-impl` will really be more or less an implementation detail of `multihash-derive`.

**Comment by thomaseizinger** [comment]
Done as part of #267.
