### ISSUE TITLE
Question about maintenance status

### ISSUE THREAD

**Issue by ebkalderon** [multiformats/rust-multihash#29]
I just stumbled across this crate after contributing to the `multihash` crate stored in [libp2p/rust-libp2p](https://github.com/libp2p/rust-libp2p/tree/master/misc/multihash). I know that the Multiformats project is part of the greater IPFS community, but so is libp2p. Both crates appear to have the same names and are developed by the same community, but are stored in separate places and the latter seems to be more frequently updated. What is the status of this crate versus the other one? Are they both one and the same?

**Comment by tomaka** [comment]
The versions of `multiaddr` and `multihash` in rust-libp2p have been copy-pasted from the `multiaddr` and `multiformats` repositories. The reason is that we wanted to be able to make changes quickly without having to go through a separate review process.

**Comment by ebkalderon** [comment]
That makes sense. Will the changes in the rust-libp2p version of `multihash` and `multiaddr` eventually make their way back into these repositories? Or is the intention that these implementations diverge permanently and the multiformat repositories be deprecated?

**Comment by tomaka** [comment]
The plan is to submit the changes upstream once rust-libp2p is stable enough.

**Comment by ebkalderon** [comment]
Sounds good. Thank you for clarifying the situation! I think we can close this issue now.
