### ISSUE TITLE
Write docs for transition to new crate structure

### ISSUE THREAD

**Issue by thomaseizinger** [multiformats/rust-multihash#290]
Created as a result of https://github.com/multiformats/rust-multihash/pull/272#pullrequestreview-1379200798.

This issue is to collect what needs to be done before we can cut the first release:

```[tasklist]
- [x] Document how users can replace the identity hasher. Done in https://github.com/multiformats/rust-multihash/pull/289.
- [ ] https://github.com/multiformats/rust-multihash/pull/320
- [ ] https://github.com/multiformats/rust-multihash/pull/321
- [ ] https://github.com/multiformats/rust-multihash/pull/319
```

**Comment by thomaseizinger** [comment]
README needs to be updated too.

**Comment by vmx** [comment]
Add a note that users upgrading could define a type alias like `type Multihash = multihash::Multihash<64>`. See 
https://github.com/multiformats/rust-multihash/pull/305#issuecomment-1531296203 for more information.

**Comment by thomaseizinger** [comment]
Where do you think would this migration docs best be written? In the README? Normally I'd add it to the changelog but that one is auto-generated here, right?

**Comment by vmx** [comment]
> Normally I'd add it to the changelog but that one is auto-generated here, right?

The changelog. I'd call it "semi-autogenerated". So what I would do is, creating the new entries as outlined in the RELEASE.md and then manually tweak it. Please note that I've tried to make it clearer (and also updated the instructions for the generation) at https://github.com/multiformats/rust-multihash/pull/314.

**Comment by thomaseizinger** [comment]
@vmx all items in here now have an open PR. Do you mind having a look and see if that is sufficient documentation so we can cut a release?

**Comment by thomaseizinger** [comment]
Closing this because all tasks are completed.
