### ISSUE TITLE
Parity Codec bumps MSRV to `1.64.0`

### ISSUE THREAD

**Issue by mriise** [multiformats/rust-multihash#306]
`proc-macro-crate` (dependency of `parity-scale-codec-derive`) has no patch number defined for `toml_edit` which made a recent patch to update `winnow` which bumps the MSRV. 

PR: https://github.com/bkchr/proc-macro-crate/pull/35

**Comment by mriise** [comment]
This is breaking the new MSRV check in CI for both #304 and #305

**Comment by thomaseizinger** [comment]
Damn, when will people stop making MSRV breaking changes in patch releases. This makes me wonder whether we should retain `parity-scale-codec` as a dependency in here.

**Comment by thomaseizinger** [comment]
I think the way forward here is to document (and test) that the MSRV for `multihash` only applies with all features disabled. That gives us control over this until we can remove `parity-scale-codec` from the library.

**Comment by vmx** [comment]
A MSRV bump was needed due to `toml_datetime`, which was then merged with https://github.com/multiformats/rust-multihash/pull/315. Hence I'm closing this issue as we are now at the MSRV of 1.64.
