### ISSUE TITLE
RUSTSEC-2024-0370: proc-macro-error is unmaintained

### ISSUE THREAD

**Issue by nazar-pc** [multiformats/rust-multihash#370]
See https://rustsec.org/advisories/RUSTSEC-2024-0370.html

Please switch to a maintained crate instead, `proc-macro-error2` seems like a trivial candidate.

**Comment by nazar-pc** [comment]
Blocked by https://github.com/autonomys/subspace/issues/3022 and https://github.com/mersinvald/aquamarine/pull/52

**Comment by Stebalien** [comment]
We've removed the dependency entirely.

**Comment by nazar-pc** [comment]
Very nice, thanks!
Is there a patch release planned that'll include it BTW?

**Comment by Stebalien** [comment]
https://github.com/multiformats/rust-multihash/pull/373
