### ISSUE TITLE
Provide an Ord instance

### ISSUE THREAD

**Issue by rklaehn** [multiformats/rust-multihash#49]
So a multihash and structs using a multihash, like rust-cid, can be used in ordered data structures.

In general, I prefer sorted data structures for more deterministic behaviour, unless the performance requirements absolutely mandate using a hashmap.

**Comment by rklaehn** [comment]
https://github.com/multiformats/rust-multihash/pull/50

**Comment by vmx** [comment]
#50 was merged.
