### ISSUE TITLE
Provide way to produce truncated hashes

### ISSUE THREAD

**Issue by rklaehn** [multiformats/rust-multihash#55]
Multihash encodes the length of the hash separately to the hash. There is no way to produce e.g. a multihash that uses Sha2_256 but only stores 16 bytes of hash data.

There should be a method `truncate` that reduces the number of bytes of the hash that is stored. This is also needed to use multihash from rust-cid. The length parameter should be the number of hash payload bytes to retain.

Not sure what the behavior should be when truncate is called with a very high value. Fail / noop?

**Comment by rklaehn** [comment]
I see that this can be implemented in terms of wrap, but I still think that it would be nice to have a dedicated method for this...

**Comment by vmx** [comment]
> There is no way to produce e.g. a multihash that uses Sha2_256 but only stores 16 bytes of hash data.

There is a way, you can call `wrap()`.

Hence I don't know if there should be a `truncate()` method at all. In case there should be one, perhaps it would be one on digest creation time, something like `digest_truncated(data, length)`.

**Comment by rklaehn** [comment]
I don't think there is a benefit in doing this at digest creation time, since you have to generate the full hash anyway. Having discovered wrap, this is more a convenience method than a necessity. The question is how common this use case is, and if a convenience method is warranted.

**Comment by vmx** [comment]
> I don't think there is a benefit in doing this at digest creation time, since you have to generate the full hash anyway.

My thoughts came from the opposite direction. I don't think there is a benefit doing the truncation outside the digest creation as you would create a digest anyway.

**Comment by rklaehn** [comment]
I can see cases where you already have a multihash from somewhere and want to truncate it, or you have two multihashes with different lengths and want to check whether they could refer to the same data.

**Comment by vmx** [comment]
I have to admit I'm not fully convinced of the use case. I'm also cautious about having a bigger public API surface.

To conclude: There currently is a way to create Multihashes with a truncated hash via `wrap()`. We could introduce a convenient methods, once it shows up as a repeated pattern.

I'm closing this issue for now.
