### ISSUE TITLE
Make multihash serializable with serde

### ISSUE THREAD

**Issue by michaelvoronov** [multiformats/rust-multihash#62]
At now, we are using serde serialization/deserialization of structures that contain `libp2p::PeerId`. In its turn `PeerId` contains two `Multihash`es, and, finally, `Multihash` is based on top of the `Storage`. But `Storage` enum is only crate pub. Could you please make it pub?
Also for implementing serde traits [it needs](https://serde.rs/remote-derive.html) explicit setter/getter of storage field inside `Multihash`, can we also do so? I can make a PR.

Thank you in advance.

**Comment by vmx** [comment]
Making Multihash easily serializable with Serde certainly is a good idea.

Why do you need direct access to `Storage`? I hope we can keep it an implementation detail of `Multihash`. Couldn't you use the public API from Multihash like e.g. `as_bytes()`?

**Comment by dignifiedquire** [comment]
It would be great to have a `serde` features on PeerId, Multihash and Cid allowing easy serializiation and deserialization, avoiding having to manually implement it

**Comment by michaelvoronov** [comment]
@vmx Initially I think that it is impossible to implement external serde traits for external types through the orpha rule. But now I found [a way](https://gist.github.com/michaelvoronov/1e844b7f94c9aa88561cf8b94c3483ae) to it with the serde `with` feature. Thank you!

Btw, I agree, it would be nice to have the `serde` feature.

**Comment by vmx** [comment]
Multihash is now serializable with Serde (it's not released yet, but it's available on `HEAD`.
