### ISSUE TITLE
use multibase for encoding/decoding

### ISSUE THREAD

**Issue by mriise** [multiformats/rust-multihash#73]
[rust multibase](https://github.com/multiformats/rust-multibase) in tests, could also be a good opportunity to remove some of the brittleness of the tests.

**Comment by vmx** [comment]
I don't quite understand what the core problem is that using multibase would help. You could see the current bytes as Base16 (Multibase Base16 without the prefix).

**Comment by vmx** [comment]
In the context of #74 it makes sense. Using Multibase instead of a custom hex parser. I think for now using the hex crate is simpler than using Multibase.

**Comment by mriise** [comment]
using multibase in tests actually doesn't have much of a point, as its a test of multihash, not multihash _and_ multibase. hex just fine for validating functionality.
