### ISSUE TITLE
Fixing warn no-run -> no_run breaks BoxedMultihashDigest

### ISSUE THREAD

**Issue by mriise** [multiformats/rust-multihash#75]
I can't say I'm too experienced with rust, but while playing around with this library I saw the warning:
```warning: unknown attribute `no-run`. Did you mean `no_run`?
  --> src\digests.rs:20:1```
and decided to fix, which then caused `cargo test` to fail at `src\digests.rs:24 BoxedMultihashDigest`.

Should code be added to the doc to fix compiler errors, or should `ignore` or `compile_fail` flags be used instead of `no_run`?

**Comment by vmx** [comment]
Thanks for reporting, I decided to use `ignore` and provide a fix right away at #76.
